version: "3"
services:
  db:
    container_name: mysql
    image: mysql:8.0.28
    platform: linux/x86_64
    restart: always
    command: --lower_case_table_names=1
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "13306:3306"
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
